# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Get static php 
      run: curl -O https://dl.static-php.dev/static-php-cli/common/php-8.3.7-fpm-linux-x86_64.tar.gz

    - name: Unpack static php 
      run: tar -zxvf php-8.3.7-fpm-linux-x86_64.tar.gz -C php-fpm
      
    - name: Make php exec  
      run:  chmod +x php-fpm/php-fpm
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
